### ISSUE TITLE
about asset source

### ISSUE THREAD

**Issue by sweet7788** [micro-frontends-demo/content#5]
hello.I think every chunk should be independent.If i add the asset source in browse-master.Run "yarn start",i can find the asset source in 3001.But in port 3000,I don't load the source.

**Comment by camjackson** [comment]
Sorry, I'm not really sure what you're getting at. Can you describe how you think things should be, versus how they are now?

**Comment by cWenyu** [comment]
> hello.I think every chunk should be independent.If i add the asset source in browse-master.Run "yarn start",i can find the asset source in 3001.But in port 3000,I don't load the source.

Hi, I have same problem with you, and I use windows 10, I got error message:
```javascript
yarn run v1.22.4
$ PORT=3002 react-app-rewired start
'PORT' is not recognized as an internal or external command
```
the problem is we need to set up port number manually in package.json for each micro frontend part, and here is my solution: 
```javascript
 "start": "set PORT=3002 && react-app-rewired start"
```
hope it will help you :smiley:
